services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env.development
    environment:
    - PORT
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: